# This workflow will build a .NET project

name: .NET-WorkFlow-DEMO

#WorkFFlow Event
on:
  #Triggers on actions
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
      - .gitignore
      
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - README.md
      - .gitignore
      
jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Display DotNet Version
      run: dotnet --version
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build Code
      run: dotnet build --no-restore
    - name: Test Code
      run: dotnet test --no-build --verbosity normal

    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
